import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/common/Layout/Layout";
import MenuPopup from "@/components/common/MenuPopup/MenuPopup";
import Blueprint from "@/components/Home/Blueprint/Blueprint";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
       <Blueprint/>
      </Layout>
    </>
  );
}
